services:
  agent-api:
    container_name: agentcore
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - agentcore-network

volumes:
  data:

networks:
  agentcore-network:
    name: agentcore-network